# version: '3.8'
services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/static
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
    # depends_on:
      # - redis

  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-data:/vol/static
    ports:
      - 80:80
    depends_on:
      - app

  # redis:
    # image: "redis:alpine"
    # ports:
      # - "6379:6379"

volumes:
  static-data:
